#!/bin/bash

apply_epp() {
    local epp="$1"
    # Écrire une seule fois sur tous les CPU en utilisant brace expansion
    echo "$epp" | tee /sys/devices/system/cpu/cpu{0..$(nproc --all -1)}/cpufreq/energy_performance_preference >/dev/null
}

while read -r line; do
    profile=$(powerprofilesctl get)
    case "$profile" in
        balanced)
            cpupower frequency-set -g powersave >/dev/null 2>&1
            apply_epp balance_performance
            ;;
        performance)
            cpupower frequency-set -g performance >/dev/null 2>&1
            apply_epp performance
            ;;
        "power-saver")
            cpupower frequency-set -g powersave >/dev/null 2>&1
            apply_epp power
            ;;
    esac
done < <(dbus-monitor --system "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/freedesktop/PowerProfiles'")

